# Generated by Django 2.2.7 on 2019-11-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularmodel',
            name='big_int',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='binary',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='decimal',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='null_bool',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='positive_int',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='positive_small_int',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='small_int',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='regularmodel',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='regularmodel',
            name='char',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
